version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  api:
    build: ./flutterhub_api
    ports:
      - "3000:3000"
    volumes:
      - ./flutterhub_api:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/flutterhub?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongodb_data: 