// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE1NiFcqtabjaN0NxjBvc8T8XeUdNVh8A',
    appId: '1:320972644360:web:ca4856eef2dc30dd1731bd',
    messagingSenderId: '320972644360',
    projectId: 'airbnb-bd47e',
    authDomain: 'airbnb-bd47e.firebaseapp.com',
    storageBucket: 'airbnb-bd47e.firebasestorage.app',
    measurementId: 'G-ENWXWQ1MHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7b7Fr6782mBBuDeINFjYgaw07H3ldR0Y',
    appId: '1:320972644360:android:809a66a5a47c84911731bd',
    messagingSenderId: '320972644360',
    projectId: 'airbnb-bd47e',
    storageBucket: 'airbnb-bd47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXnS7fxMGYJ0Ti1LIwLfweegG1Rqq3v0s',
    appId: '1:320972644360:ios:24006b45786c6fd01731bd',
    messagingSenderId: '320972644360',
    projectId: 'airbnb-bd47e',
    storageBucket: 'airbnb-bd47e.firebasestorage.app',
    iosBundleId: 'com.example.flutterhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXnS7fxMGYJ0Ti1LIwLfweegG1Rqq3v0s',
    appId: '1:320972644360:ios:24006b45786c6fd01731bd',
    messagingSenderId: '320972644360',
    projectId: 'airbnb-bd47e',
    storageBucket: 'airbnb-bd47e.firebasestorage.app',
    iosBundleId: 'com.example.flutterhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE1NiFcqtabjaN0NxjBvc8T8XeUdNVh8A',
    appId: '1:320972644360:web:2daecdb4f16877d91731bd',
    messagingSenderId: '320972644360',
    projectId: 'airbnb-bd47e',
    authDomain: 'airbnb-bd47e.firebaseapp.com',
    storageBucket: 'airbnb-bd47e.firebasestorage.app',
    measurementId: 'G-HWTDFT7FLW',
  );
}
